dist: bionic
language: python
cache: pip

python:
  - '3.8' # this should be in sync with the Dockerfile base image

services:
  - docker

script:
  - if [[ -z "$IMAGE" ]]; then exit 1; fi
  - docker build -t $IMAGE .

deploy:
  - provider: script
    script: .travis/docker-push.sh
    on:
      branch: 'master'
  - provider: script
    script: .travis/docker-push.sh
    on:
      tags: true
